// SPDX-License-Identifier: MPL-2.0

//! System-level Tauri commands.
//!
//! Commands: copy_to_clipboard, get_clipboard, open_url,
//!           mark_context_menu_used, get_session_state, toggle_fullscreen.

mod clipboard;
mod preferences;
mod session;
mod url;
mod window;

#[cfg(test)]
mod tests;

// Re-export all public items (including __cmd__* wrappers generated by
// #[tauri::command]) so that generate_handler![] can resolve them at
// the `commands::system_cmds::*` path used in lib.rs.
pub use clipboard::*;
pub use preferences::*;
pub use session::*;
pub use url::*;
pub use window::*;
