// SPDX-License-Identifier: MPL-2.0

/**
 * Test stub for $lib/paraglide/runtime.
 *
 * The real module is generated by the Paraglide Vite plugin at build time and
 * is not available during vitest runs. This stub provides the minimal surface
 * used by locale.svelte.ts so unit tests can import and exercise that module
 * without a real Paraglide build.
 *
 * Do NOT import this file in production code — it is resolved only via the
 * vitest `alias` configuration in vitest.config.ts.
 */

type Locale = 'en' | 'fr';

let _locale: Locale = 'en';

export function getLocale(): Locale {
  return _locale;
}

export function overwriteGetLocale(_fn: () => Locale): void {
  // No-op in tests: locale.svelte.ts calls this at module load to wire Paraglide's
  // getLocale() to the $state. The mock already returns _locale from getLocale(),
  // so no substitution is needed here.
}

export function setLocale(locale: Locale, options?: { reload?: boolean }): void {
  if (options?.reload !== false && typeof window !== 'undefined') {
    // Fail loudly in tests if caller forgets { reload: false }.
    // The real Paraglide runtime calls window.location.reload() by default,
    // which causes an infinite loop in a Tauri SPA. Tests must always pass
    // { reload: false } explicitly.
    throw new Error(
      `[paraglide mock] setLocale('${locale}') called without { reload: false }. ` +
        `The real runtime would reload the page — this is a bug in TauTerm code.`,
    );
  }
  _locale = locale;
}
