// SPDX-License-Identifier: MPL-2.0

/**
 * Test stub for $lib/paraglide/runtime.
 *
 * The real module is generated by the Paraglide Vite plugin at build time and
 * is not available during vitest runs. This stub provides the minimal surface
 * used by locale.svelte.ts so unit tests can import and exercise that module
 * without a real Paraglide build.
 *
 * Do NOT import this file in production code — it is resolved only via the
 * vitest `alias` configuration in vitest.config.ts.
 */

type Locale = 'en' | 'fr';

let _locale: Locale = 'en';

export function getLocale(): Locale {
  return _locale;
}

export function setLocale(locale: Locale): void {
  _locale = locale;
}
