// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	createTab: (config: CreateTabConfig) => typedError<TabState, TauTermError>(__TAURI_INVOKE("create_tab", { config })),
	closeTab: (tabId: TabId) => typedError<null, TauTermError>(__TAURI_INVOKE("close_tab", { tabId })),
	renameTab: (tabId: TabId, label: string | null) => typedError<TabState, TauTermError>(__TAURI_INVOKE("rename_tab", { tabId, label })),
	setPaneLabel: (paneId: PaneId, label: string | null) => typedError<TabState, TauTermError>(__TAURI_INVOKE("set_pane_label", { paneId, label })),
	reorderTab: (tabId: TabId, newOrder: number) => typedError<null, TauTermError>(__TAURI_INVOKE("reorder_tab", { tabId, newOrder })),
	splitPane: (paneId: PaneId, direction: SplitDirection) => typedError<TabState, TauTermError>(__TAURI_INVOKE("split_pane", { paneId, direction })),
	closePane: (paneId: PaneId) => typedError<{
	id: TabId,
	// User-defined label. `None` = auto-title from active pane's OSC title.
	label: string | null,
	activePaneId: PaneId,
	// Display order (lower = further left in the tab bar).
	order: number,
	// Pane layout tree.
	layout: PaneNode,
} | null, TauTermError>(__TAURI_INVOKE("close_pane", { paneId })),
	setActiveTab: (tabId: TabId) => typedError<null, TauTermError>(__TAURI_INVOKE("set_active_tab", { tabId })),
	setActivePane: (paneId: PaneId) => typedError<null, TauTermError>(__TAURI_INVOKE("set_active_pane", { paneId })),
	/**
	 *  FS-PTY-008: Detect whether a non-shell foreground process is active in a pane.
	 * 
	 *  Returns `true` when the PTY foreground process group (from `tcgetpgrp`) differs
	 *  from the shell's PID — indicating that the user has run a command that has not
	 *  yet returned to the shell prompt.
	 * 
	 *  Returns `false` when:
	 *  - The pane does not exist.
	 *  - The pane is not in `Running` state (already terminated, closing, etc.).
	 *  - The pane is an SSH pane (no local PTY master fd).
	 *  - The shell PID is unknown (session type does not track it).
	 * 
	 *  The `tcgetpgrp` syscall is performed inside the registry, delegated through
	 *  `PtySession::foreground_pgid()` in the platform layer — no `unsafe` here.
	 */
	hasForegroundProcess: (paneId: PaneId) => typedError<boolean, TauTermError>(__TAURI_INVOKE("has_foreground_process", { paneId })),
	sendInput: (paneId: PaneId, data: number[]) => typedError<null, TauTermError>(__TAURI_INVOKE("send_input", { paneId, data })),
	scrollPane: (paneId: PaneId, offset: number) => typedError<ScrollPositionState, TauTermError>(__TAURI_INVOKE("scroll_pane", { paneId, offset })),
	scrollToBottom: (paneId: PaneId) => typedError<null, TauTermError>(__TAURI_INVOKE("scroll_to_bottom", { paneId })),
	searchPane: (paneId: PaneId, query: SearchQuery) => typedError<SearchMatch[], TauTermError>(__TAURI_INVOKE("search_pane", { paneId, query })),
	getPaneScreenSnapshot: (paneId: PaneId) => typedError<ScreenSnapshot, TauTermError>(__TAURI_INVOKE("get_pane_screen_snapshot", { paneId })),
	// Resize a pane's PTY. Debounced by the backend (§6.5).
	resizePane: (paneId: PaneId, cols: number, rows: number, pixelWidth: number, pixelHeight: number) => typedError<null, TauTermError>(__TAURI_INVOKE("resize_pane", { paneId, cols, rows, pixelWidth, pixelHeight })),
	/**
	 *  P-HT-6: Frontend frame acknowledgement.
	 * 
	 *  Called by the frontend after each successful `flushRafQueue()` paint.
	 *  Updates the pane's last-ack timestamp so the backend can detect frontend overload.
	 * 
	 *  Fire-and-forget from the frontend — always returns `Ok(())`.
	 *  If the pane no longer exists (race with close), silently ignored.
	 */
	frameAck: (paneId: PaneId) => typedError<null, TauTermError>(__TAURI_INVOKE("frame_ack", { paneId })),
	// Production variant — registered when `e2e-testing` feature is NOT active.
	openSshConnection: (paneId: PaneId, connectionId: ConnectionId, pixelWidth: number | null, pixelHeight: number | null) => typedError<null, TauTermError>(__TAURI_INVOKE("open_ssh_connection", { paneId, connectionId, pixelWidth, pixelHeight })),
	closeSshConnection: (paneId: PaneId) => typedError<null, TauTermError>(__TAURI_INVOKE("close_ssh_connection", { paneId })),
	reconnectSsh: (paneId: PaneId) => typedError<null, TauTermError>(__TAURI_INVOKE("reconnect_ssh", { paneId })),
	provideCredentials: (paneId: PaneId, credentials: Credentials) => typedError<null, TauTermError>(__TAURI_INVOKE("provide_credentials", { paneId, credentials })),
	/**
	 *  Provide a passphrase for an encrypted SSH private key (FS-SSH-019a).
	 * 
	 *  Called by the frontend in response to a `passphrase-prompt` event.
	 *  The passphrase is forwarded to the connect task via the oneshot channel
	 *  stored in `SshManager::pending_passphrases`.
	 */
	providePassphrase: (paneId: PaneId, passphrase: string, saveInKeychain: boolean) => typedError<null, TauTermError>(__TAURI_INVOKE("provide_passphrase", { paneId, passphrase, saveInKeychain })),
	/**
	 *  Accept the host key for a pane that is pending TOFU verification.
	 * 
	 *  ## Security (SEC-SSH-CH-002)
	 *  The key bytes are retrieved from `SshManager::pending_host_keys` — they were
	 *  stored by the Rust-side `check_server_key` callback and are NOT taken from the
	 *  IPC payload. This prevents a hostile frontend from accepting an arbitrary key.
	 * 
	 *  After persisting the key to `known_hosts`, returns `Ok(())`. The frontend
	 *  must then call `open_ssh_connection` again to reconnect (two-phase TOFU).
	 */
	acceptHostKey: (paneId: PaneId) => typedError<null, TauTermError>(__TAURI_INVOKE("accept_host_key", { paneId })),
	// Reject the host key for a pane — abort the pending connection.
	rejectHostKey: (paneId: PaneId) => typedError<null, TauTermError>(__TAURI_INVOKE("reject_host_key", { paneId })),
	/**
	 *  Dismiss an SSH algorithm warning for a pane.
	 * 
	 *  This command is a no-op in v1 — the warning is purely informational and
	 *  requires no server-side action. It exists so the frontend can call it and
	 *  receive an Ok without causing an IPC error.
	 */
	dismissSshAlgorithmWarning: (paneId: PaneId) => typedError<null, TauTermError>(__TAURI_INVOKE("dismiss_ssh_algorithm_warning", { paneId })),
	getConnections: () => typedError<SshConnectionConfig[], TauTermError>(__TAURI_INVOKE("get_connections")),
	saveConnection: (config: SshConnectionConfig) => typedError<ConnectionId, TauTermError>(__TAURI_INVOKE("save_connection", { config })),
	deleteConnection: (connectionId: ConnectionId) => typedError<null, TauTermError>(__TAURI_INVOKE("delete_connection", { connectionId })),
	/**
	 *  Returns the full `SshConnectionConfig` of the new connection rather than just its ID,
	 *  allowing the frontend to update its connection list in a single round-trip.
	 *  The IPC spec table lists `ConnectionId` as the return type, but returning the full
	 *  config is strictly better UX and avoids a redundant `get_connections` call.
	 */
	duplicateConnection: (connectionId: ConnectionId) => typedError<SshConnectionConfig, TauTermError>(__TAURI_INVOKE("duplicate_connection", { connectionId })),
	/**
	 *  SEC-CRED-004: Store a connection password in the OS keychain.
	 * 
	 *  Called by the frontend after `save_connection` succeeds, when the user has
	 *  entered a password in the connection form. The password is stored under the
	 *  key `tauterm:ssh:{connection_id}:{username}` via the platform credential store.
	 * 
	 *  Validation rejects empty IDs, empty passwords, and passwords exceeding
	 *  `MAX_PASSWORD_LEN` bytes. Errors are non-fatal from the frontend's perspective
	 *  (keychain daemon may be unavailable), but are reported as typed errors so the
	 *  caller can decide.
	 */
	storeConnectionPassword: (connectionId: ConnectionId, username: string, password: string) => typedError<null, TauTermError>(__TAURI_INVOKE("store_connection_password", { connectionId, username, password })),
	getPreferences: () => typedError<Preferences, TauTermError>(__TAURI_INVOKE("get_preferences")),
	updatePreferences: (patch: PreferencesPatch) => typedError<Preferences, TauTermError>(__TAURI_INVOKE("update_preferences", { patch })),
	getThemes: () => typedError<UserTheme[], TauTermError>(__TAURI_INVOKE("get_themes")),
	saveTheme: (theme: UserTheme) => typedError<null, TauTermError>(__TAURI_INVOKE("save_theme", { theme })),
	deleteTheme: (name: string) => typedError<null, TauTermError>(__TAURI_INVOKE("delete_theme", { name })),
	getSessionState: () => typedError<SessionState, TauTermError>(__TAURI_INVOKE("get_session_state")),
	copyToClipboard: (text: string) => typedError<null, TauTermError>(__TAURI_INVOKE("copy_to_clipboard", { text })),
	getClipboard: () => typedError<string, TauTermError>(__TAURI_INVOKE("get_clipboard")),
	/**
	 *  Open a URL in the system browser. Scheme is validated (§8.1 / FS-VT-073).
	 * 
	 *  `pane_id` — the pane from which the link was activated. When provided, the
	 *  `file://` scheme is allowed only if that pane is a local PTY session. When
	 *  absent (e.g. called without a pane context), `file://` is always rejected.
	 */
	openUrl: (url: string, paneId: string | null) => typedError<null, TauTermError>(__TAURI_INVOKE("open_url", { url, paneId })),
	markContextMenuUsed: () => typedError<null, TauTermError>(__TAURI_INVOKE("mark_context_menu_used")),
	/**
	 *  Toggle full-screen mode on the main window (FS-FULL-009).
	 * 
	 *  Queries the current full-screen state, flips it, persists the preference,
	 *  and emits a `fullscreen-state-changed` event after a short delay that lets
	 *  the WM confirm the geometry transition.
	 * 
	 *  SIGWINCH is intentionally NOT broadcast here — the frontend ResizeObserver
	 *  will observe the geometry change and call `resize_pane` → `ResizeDebouncer`.
	 */
	toggleFullscreen: () => typedError<FullscreenState, TauTermError>(__TAURI_INVOKE("toggle_fullscreen")),
};

/** Events */
export const events = {
	bellTriggered: makeEvent<BellTriggeredEvent>("bell-triggered"),
	credentialPrompt: makeEvent<CredentialPromptEvent>("credential-prompt"),
	cursorStyleChanged: makeEvent<CursorStyleChangedEvent>("cursor-style-changed"),
	fullscreenStateChanged: makeEvent<FullscreenStateChangedEvent>("fullscreen-state-changed"),
	hostKeyPrompt: makeEvent<HostKeyPromptEvent>("host-key-prompt"),
	modeStateChanged: makeEvent<ModeStateChangedEvent>("mode-state-changed"),
	notificationChanged: makeEvent<NotificationChangedEvent>("notification-changed"),
	osc52WriteRequested: makeEvent<Osc52WriteRequestedEvent>("osc52-write-requested"),
	passphrasePrompt: makeEvent<PassphrasePromptEvent>("passphrase-prompt"),
	preferencesChanged: makeEvent<PreferencesChangedEvent>("preferences-changed"),
	screenUpdate: makeEvent<ScreenUpdateEvent>("screen-update"),
	scrollPositionChanged: makeEvent<ScrollPositionChangedEvent>("scroll-position-changed"),
	sessionStateChanged: makeEvent<SessionStateChangedEvent>("session-state-changed"),
	sshReconnected: makeEvent<SshReconnectedEvent>("ssh-reconnected"),
	sshStateChanged: makeEvent<SshStateChangedEvent>("ssh-state-changed"),
	sshWarning: makeEvent<SshWarningEvent>("ssh-warning"),
};

/* Types */
/**
 *  Partial update for appearance preferences — only the fields provided are changed.
 * 
 *  Using a dedicated patch type (instead of `Option<AppearancePrefs>` in `PreferencesPatch`)
 *  allows field-by-field updates without read-before-write: e.g. changing the language
 *  without knowing or sending the current font size.
 */
export type AppearancePatch = {
	fontFamily?: FontFamily | null,
	fontSize?: number | null,
	cursorStyle?: CursorStyle | null,
	cursorBlinkMs?: number | null,
	themeName?: ThemeName | null,
	opacity?: number | null,
	language?: Language | null,
	contextMenuHintShown?: boolean | null,
	fullscreen?: boolean | null,
	hideCursorWhileTyping?: boolean | null,
	showPaneTitleBar?: boolean | null,
	fullscreenChromeBehavior?: FullscreenChromeBehavior | null,
};

// Appearance-related preferences.
export type AppearancePrefs = {
	fontFamily?: FontFamily,
	fontSize?: number,
	cursorStyle?: CursorStyle,
	// Cursor blink period in milliseconds (FS-VT-032). Default: 530ms.
	cursorBlinkMs?: number,
	// Name of the active theme.
	themeName?: ThemeName,
	// Background opacity (0.0–1.0).
	opacity?: number,
	// UI language (FS-I18N-006: enum, not free String).
	language?: Language,
	/**
	 *  Whether the context menu hint has been shown at least once.
	 *  Used to suppress the first-use onboarding hint after the user has seen it.
	 */
	contextMenuHintShown?: boolean,
	/**
	 *  Whether the window should be in full-screen mode (FS-FULL-009).
	 *  `#[serde(default)]` ensures existing preferences files without this field
	 *  deserialize successfully with `false`.
	 */
	fullscreen?: boolean,
	/**
	 *  Hide the mouse cursor while the user is typing in the terminal (UI-2).
	 *  Restored immediately on `mousemove`. Default: `true`.
	 */
	hideCursorWhileTyping?: boolean,
	// Whether the pane title bar is visible. Default: `true`.
	showPaneTitleBar?: boolean,
	/**
	 *  How the tab bar and status bar behave in fullscreen mode.
	 *  `#[serde(default)]` ensures existing preferences files without this field
	 *  deserialize successfully with `FullscreenChromeBehavior::AutoHide`.
	 */
	fullscreenChromeBehavior?: FullscreenChromeBehavior,
};

/**
 *  Emitted when the terminal produces a BEL character, rate-limited to at most
 *  one event per 100 ms per pane (FS-VT-090).
 */
export type BellTriggeredEvent = {
	paneId: PaneId,
};

export type BellType = 
// No bell notification.
"none" | 
// Visual flash (default).
"visual" | 
// System audio bell.
"audio" | 
// Both visual and audio.
"both";

// Serializable SGR cell attributes sent to the frontend.
export type CellAttrsDto = CellAttrsDto_Serialize | CellAttrsDto_Deserialize;

// Serializable SGR cell attributes sent to the frontend.
export type CellAttrsDto_Deserialize = {
	fg: ColorDto | null,
	bg: ColorDto | null,
	bold?: boolean | null,
	dim?: boolean | null,
	italic?: boolean | null,
	underline?: number | null,
	blink?: boolean | null,
	inverse?: boolean | null,
	hidden?: boolean | null,
	strikethrough?: boolean | null,
	underlineColor: ColorDto | null,
};

// Serializable SGR cell attributes sent to the frontend.
export type CellAttrsDto_Serialize = {
	fg?: ColorDto | null,
	bg?: ColorDto | null,
	bold?: boolean | null,
	dim?: boolean | null,
	italic?: boolean | null,
	underline?: number | null,
	blink?: boolean | null,
	inverse?: boolean | null,
	hidden?: boolean | null,
	strikethrough?: boolean | null,
	underlineColor?: ColorDto | null,
};

// A single updated cell in the screen buffer.
export type CellUpdate = CellUpdate_Serialize | CellUpdate_Deserialize;

// A single updated cell in the screen buffer.
export type CellUpdate_Deserialize = {
	row: number,
	col: number,
	content: string,
	/**
	 *  Visual width of the cell: 1 = normal, 2 = wide (CJK/emoji), 0 = phantom
	 *  (continuation slot of a wide character — the frontend must leave it blank).
	 */
	width: number,
	attrs: CellAttrsDto_Deserialize,
	// OSC 8 hyperlink URI for this cell, if any.
	hyperlink: string | null,
};

// A single updated cell in the screen buffer.
export type CellUpdate_Serialize = {
	row: number,
	col: number,
	content: string,
	/**
	 *  Visual width of the cell: 1 = normal, 2 = wide (CJK/emoji), 0 = phantom
	 *  (continuation slot of a wide character — the frontend must leave it blank).
	 */
	width: number,
	attrs: CellAttrsDto_Serialize,
	// OSC 8 hyperlink URI for this cell, if any.
	hyperlink?: string | null,
};

// Terminal color value.
export type Color = 
/**
 *  One of the 16 standard ANSI colors (palette index 0–15).
 *  Colors 0–7 = normal, 8–15 = bright.
 */
{ type: "ansi"; index: number } | 
// One of the 256 xterm colors (palette index 0–255).
{ type: "ansi256"; index: number } | 
// 24-bit truecolor (ITU T.416 / SGR 38;2;R;G;B).
{ type: "rgb"; r: number; g: number; b: number };

// Color value — ANSI 16, 256-color index, or 24-bit RGB.
export type ColorDto = { type: "default" } | { type: "ansi"; index: number } | { type: "ansi256"; index: number } | { type: "rgb"; r: number; g: number; b: number };

// Identifies a saved SSH connection configuration.
export type ConnectionId = string;

// Configuration for creating a new tab.
export type CreateTabConfig = {
	// Optional initial label. `None` = use process title via OSC.
	label: string | null,
	// Initial terminal dimensions.
	cols: number,
	rows: number,
	/**
	 *  Cell pixel dimensions for `TIOCSWINSZ` / SSH `pty-req`.
	 *  Defaults to 0 (unknown) — applications that use pixel-perfect rendering
	 *  (e.g. Sixel, ReGIS) will report incorrect cell sizes until the frontend
	 *  sends accurate values.
	 */
	pixelWidth?: number,
	pixelHeight?: number,
	/**
	 *  Optional shell executable path. `None` = use `$SHELL` or fall back to `/bin/sh`.
	 *  Must be an absolute path to an executable file.
	 */
	shell?: string | null,
	/**
	 *  Whether to launch a login shell (first tab) or non-login interactive shell
	 *  (subsequent tabs and panes). Default: false.
	 */
	login?: boolean,
	/**
	 *  If set, inherit the working directory from this pane (with `/proc` fallback
	 *  when OSC 7 is unavailable). FS-VT-064.
	 */
	sourcePaneId?: PaneId | null,
};

// Emitted when the SSH authentication flow needs credentials from the user.
export type CredentialPromptEvent = CredentialPromptEvent_Serialize | CredentialPromptEvent_Deserialize;

// Emitted when the SSH authentication flow needs credentials from the user.
export type CredentialPromptEvent_Deserialize = {
	paneId: PaneId,
	host: string,
	username: string,
	// Optional prompt text from the server (keyboard-interactive).
	prompt: string | null,
	/**
	 *  `true` when a previous authentication attempt failed (stale/wrong password).
	 *  The frontend uses this to show an error indicator in the credential dialog.
	 */
	failed: boolean,
	/**
	 *  `true` when the OS keychain is available so the frontend can offer a
	 *  "Save in keychain" checkbox (FS-CRED-007).
	 */
	isKeychainAvailable: boolean,
};

// Emitted when the SSH authentication flow needs credentials from the user.
export type CredentialPromptEvent_Serialize = {
	paneId: PaneId,
	host: string,
	username: string,
	// Optional prompt text from the server (keyboard-interactive).
	prompt?: string | null,
	/**
	 *  `true` when a previous authentication attempt failed (stale/wrong password).
	 *  The frontend uses this to show an error indicator in the credential dialog.
	 */
	failed: boolean,
	/**
	 *  `true` when the OS keychain is available so the frontend can offer a
	 *  "Save in keychain" checkbox (FS-CRED-007).
	 */
	isKeychainAvailable: boolean,
};

/**
 *  Credentials for SSH authentication.
 * 
 *  SECURITY: `Debug` is implemented manually to redact sensitive fields.
 *  Never use `#[derive(Debug)]` on this struct — it would expose passwords in logs.
 *  `ZeroizeOnDrop` ensures all secret fields are overwritten in memory when the struct is dropped
 *  (FS-CRED-003).
 */
export type Credentials = {
	username: string,
	password: string | null,
	privateKeyPath: string | null,
	// Whether the user wants the password saved to the OS keychain (FS-CRED-007).
	saveInKeychain?: boolean,
};

// Serializable cursor state.
export type CursorState = {
	row: number,
	col: number,
	visible: boolean,
	shape: number,
	blink: boolean,
};

export type CursorStyle = "block" | "underline" | "bar";

/**
 *  Emitted when the cursor shape changes via DECSCUSR (FS-VT-030).
 * 
 *  `shape` carries the raw DECSCUSR parameter (0–6):
 *  - 0/1 = blinking block, 2 = steady block
 *  - 3 = blinking underline, 4 = steady underline
 *  - 5 = blinking bar, 6 = steady bar
 */
export type CursorStyleChangedEvent = {
	paneId: PaneId,
	// Raw DECSCUSR value (0–6).
	shape: number,
};

/**
 *  A validated font family name (may be empty).
 * 
 *  Constraints: max 256 bytes, no control characters.
 */
export type FontFamily = string;

export type FullscreenChromeBehavior = 
// Tab bar and status bar auto-hide when entering fullscreen (default).
"autoHide" | 
// Tab bar and status bar remain visible in fullscreen.
"alwaysVisible";

/**
 *  Query result for the current window full-screen state.
 *  Returned synchronously by `toggle_fullscreen` (FS-FULL-009).
 */
export type FullscreenState = {
	isFullscreen: boolean,
};

/**
 *  Emitted after the window geometry transition to full-screen or windowed.
 *  Informational — the frontend ResizeObserver + `resize_pane` handle SIGWINCH.
 */
export type FullscreenStateChangedEvent = {
	isFullscreen: boolean,
};

// Emitted on first connection or when the host key has changed.
export type HostKeyPromptEvent = {
	paneId: PaneId,
	// Connection config ID — frontend uses it to reopen the connection after TOFU acceptance.
	connectionId: ConnectionId,
	host: string,
	keyType: string,
	fingerprint: string,
	// `true` if this is a key change (potential MITM); `false` for first-time TOFU.
	isChanged: boolean,
};

// Partial update for keyboard preferences — only the fields provided are changed.
export type KeyboardPatch = {
	bindings?: { [key in string]: string } | null,
};

// Keyboard shortcut preferences.
export type KeyboardPrefs = {
	bindings?: { [key in string]: string },
};

/**
 *  Supported UI languages. Extend this enum when adding new locales.
 *  This type is used across IPC — it MUST NOT be replaced with a plain `String`.
 */
export type Language = "en" | "fr";

/**
 *  Emitted when any terminal mode relevant to the frontend changes.
 *  The frontend uses these flags for keyboard encoding, mouse reporting,
 *  focus events, and bracketed paste (FS-KBD-007, FS-KBD-010, FS-VT-080–086, FS-CLIP-008).
 */
export type ModeStateChangedEvent = {
	paneId: PaneId,
	// DECCKM (mode 1): application cursor keys active.
	decckm: boolean,
	// DECKPAM active (ESC =): application keypad mode.
	deckpam: boolean,
	// Mouse reporting mode.
	mouseReporting: MouseReportingMode,
	// Mouse encoding format.
	mouseEncoding: MouseEncoding,
	// DECSET 1004: focus events active.
	focusEvents: boolean,
	// DECSET 2004: bracketed paste mode active.
	bracketedPaste: boolean,
};

/**
 *  Mouse event encoding format.
 * 
 *  Serializes to camelCase strings for IPC: `"x10"`, `"sgr"`, `"urxvt"`.
 */
export type MouseEncoding = 
// Classic X10 encoding (limited to col/row ≤ 223).
"x10" | 
// SGR encoding (mode 1006) — preferred; no coordinate limit.
"sgr" | 
// URXVT encoding (mode 1015).
"urxvt";

/**
 *  Mouse reporting modes (mutually exclusive; higher wins).
 * 
 *  Serializes to camelCase strings for IPC: `"none"`, `"x10"`, `"normal"`,
 *  `"buttonEvent"`, `"anyEvent"`.
 */
export type MouseReportingMode = 
// No mouse reporting.
"none" | 
// X10 compatibility (mode 9): button press only.
"x10" | 
// Normal tracking (mode 1000): press + release.
"normal" | 
// Button event tracking (mode 1002): press, release, drag.
"buttonEvent" | 
// Any event tracking (mode 1003): all motion included.
"anyEvent";

// Emitted when a pane's notification state changes (bell, background output, exit).
export type NotificationChangedEvent = {
	tabId: TabId,
	paneId: PaneId,
	// `None` means the notification was cleared.
	notification: PaneNotificationDto | null,
};

/**
 *  Emitted when the terminal requests a clipboard write via OSC 52 (FS-VT-075).
 *  Only emitted when `allow_osc52_write` is `true` in `VtProcessor`.
 */
export type Osc52WriteRequestedEvent = {
	paneId: PaneId,
	// Decoded UTF-8 clipboard payload.
	data: string,
};

// Identifies a pane within a tab.
export type PaneId = string;

// The lifecycle state of a local PTY pane.
export type PaneLifecycleState = 
// PTY is being allocated and the child process is being forked.
{ type: "spawning" } | 
// PTY I/O is active; input and output are flowing.
{ type: "running" } | 
/**
 *  Child process exited. Pane is visible with exit code.
 *  User may restart (→ Spawning) or close (→ Closed).
 */
{ type: "terminated"; 
// Process exit code. `None` if the exit code could not be determined.
exit_code: number | null; 
// Optional human-readable error description.
error: string | null } | 
/**
 *  User requested close; SIGHUP was sent to the process group.
 *  Waiting for the process to exit.
 */
{ type: "closing" } | 
// PTY is fully closed; all resources have been released.
{ type: "closed" };

// Arborescent pane layout node (§4.5.1 of ARCHITECTURE.md).
export type PaneNode = 
// A leaf node containing a single pane.
{ type: "leaf"; paneId: PaneId; state: PaneState } | 
// An interior split node containing two children.
{ type: "split"; direction: SplitDirection; 
// Size ratio of the first child (0.0–1.0).
ratio: number; first: PaneNode; second: PaneNode };

export type PaneNotificationDto = { type: "bell" } | { type: "backgroundOutput" } | 
/**
 *  Process exited — clean (exit_code = Some(0)), error (exit_code = Some(n)), or
 *  killed by signal (exit_code = None, signal_name = Some("SIGKILL"), etc.).
 */
{ type: "processExited"; 
// `None` if the process was killed by a signal (WIFSIGNALED).
exitCode: number | null; 
/**
 *  Signal name (e.g. `"SIGKILL"`, `"SIGHUP"`) when killed by a signal.
 *  `None` for normal exits.
 */
signalName: string | null };

// Serializable pane state — sent to the frontend via IPC.
export type PaneState = {
	paneId: PaneId,
	lifecycle: PaneLifecycleState,
	/**
	 *  Title from OSC sequences. `None` until first OSC title received.
	 *  Serialized as `processTitle` to match the TypeScript IPC contract.
	 */
	processTitle: string | null,
	// SSH session state. `None` for local PTY panes.
	sshState: SshLifecycleState | null,
	// Current scroll offset in scrollback lines (0 = bottom/live view).
	scrollOffset: number,
	/**
	 *  Current working directory as reported by OSC 7. `None` until the shell
	 *  sends the first CWD notification.
	 */
	cwd?: string | null,
	/**
	 *  User-defined label. `None` until the user sets one.
	 *  Serialized as `label`; overrides the auto-derived title.
	 */
	label?: string | null,
};

// Emitted when SSH pubkey auth requires a passphrase for an encrypted private key (FS-SSH-019a).
export type PassphrasePromptEvent = {
	paneId: PaneId,
	// Filename of the private key — NEVER the full path (security: no usernames in logs).
	keyPathLabel: string,
	// `true` when a previous passphrase attempt failed.
	failed: boolean,
	/**
	 *  `true` when the OS keychain is available so the frontend can offer a
	 *  "Save in keychain" checkbox (FS-CRED-007).
	 */
	isKeychainAvailable: boolean,
};

// Top-level user preferences.
export type Preferences = {
	/**
	 *  Schema version stamped at save time (FS-PREF-schema, ARCH-3).
	 *  Absence of the field (`None` after deserialization) is treated as v0
	 *  by the migration layer. Defaults to 0 so the `Default` impl never needs
	 *  to know the current version — the store stamps it on every save.
	 */
	schemaVersion?: number,
	appearance?: AppearancePrefs,
	terminal?: TerminalPrefs,
	keyboard?: KeyboardPrefs,
	// Saved SSH connections. Authoritative source — `SshManager` reads/writes these.
	connections?: SshConnectionConfig[],
	// User-defined themes.
	themes?: UserTheme[],
};

/**
 *  Emitted when preferences are changed externally (another TauTerm instance).
 * 
 *  The frontend replaces its in-memory preferences with the payload to stay in
 *  sync without requiring a manual reload.
 */
export type PreferencesChangedEvent = {
	preferences: Preferences,
};

/**
 *  A partial preferences update (only the fields the user changed).
 *  All fields are optional so the frontend can send minimal payloads.
 */
export type PreferencesPatch = {
	appearance?: AppearancePatch | null,
	terminal?: TerminalPatch | null,
	keyboard?: KeyboardPatch | null,
};

// A snapshot of the visible screen content, used for `get_pane_screen_snapshot`.
export type ScreenSnapshot = {
	cols: number,
	rows: number,
	// Row-major flat array: rows × cols cells.
	cells: SnapshotCell[],
	cursorRow: number,
	cursorCol: number,
	cursorVisible: boolean,
	cursorShape: number,
	scrollbackLines: number,
	scrollOffset: number,
};

/**
 *  Emitted by the PTY read task after processing terminal output.
 *  Carries either dirty cell diffs or a full snapshot flag.
 */
export type ScreenUpdateEvent = ScreenUpdateEvent_Serialize | ScreenUpdateEvent_Deserialize;

/**
 *  Emitted by the PTY read task after processing terminal output.
 *  Carries either dirty cell diffs or a full snapshot flag.
 */
export type ScreenUpdateEvent_Deserialize = {
	paneId: PaneId,
	// Individual cell updates within the dirty region.
	cells: CellUpdate_Deserialize[],
	// Cursor position after processing.
	cursor: CursorState,
	/**
	 *  Total scrollback lines available after this update.
	 * 
	 *  Allows the frontend to keep the scrollbar accurate when new lines are
	 *  appended to the scrollback buffer while the user is scrolled up
	 *  (scroll-freeze policy).
	 */
	scrollbackLines: number,
	/**
	 *  True when the entire screen must be repainted (alternate screen switch,
	 *  resize, or ED2). The frontend uses this to reset scroll offset and
	 *  rebuild `gridRows` fully rather than applying a partial diff.
	 */
	isFullRedraw: boolean,
	/**
	 *  Terminal grid dimensions when this event was produced.
	 *  Used by the frontend as the authoritative stride for applyUpdates — eliminates
	 *  stride mismatch from the optimistic cols/rows update in sendResize().
	 */
	cols: number,
	rows: number,
	// 0 for live PTY events. Equals `pane.scroll_offset` for scroll-triggered viewport redraws.
	scrollOffset: number,
};

/**
 *  Emitted by the PTY read task after processing terminal output.
 *  Carries either dirty cell diffs or a full snapshot flag.
 */
export type ScreenUpdateEvent_Serialize = {
	paneId: PaneId,
	// Individual cell updates within the dirty region.
	cells: CellUpdate_Serialize[],
	// Cursor position after processing.
	cursor: CursorState,
	/**
	 *  Total scrollback lines available after this update.
	 * 
	 *  Allows the frontend to keep the scrollbar accurate when new lines are
	 *  appended to the scrollback buffer while the user is scrolled up
	 *  (scroll-freeze policy).
	 */
	scrollbackLines: number,
	/**
	 *  True when the entire screen must be repainted (alternate screen switch,
	 *  resize, or ED2). The frontend uses this to reset scroll offset and
	 *  rebuild `gridRows` fully rather than applying a partial diff.
	 */
	isFullRedraw: boolean,
	/**
	 *  Terminal grid dimensions when this event was produced.
	 *  Used by the frontend as the authoritative stride for applyUpdates — eliminates
	 *  stride mismatch from the optimistic cols/rows update in sendResize().
	 */
	cols: number,
	rows: number,
	// 0 for live PTY events. Equals `pane.scroll_offset` for scroll-triggered viewport redraws.
	scrollOffset: number,
};

// Emitted when the scrollback viewport position changes.
export type ScrollPositionChangedEvent = {
	paneId: PaneId,
	// Current scroll offset (lines from bottom; 0 = at bottom).
	offset: number,
	// Total scrollback lines available.
	scrollbackLines: number,
};

// Scroll position state returned by `scroll_pane`.
export type ScrollPositionState = {
	offset: number,
	scrollbackLines: number,
};

// A single search match position.
export type SearchMatch = {
	// Row index in the scrollback (0-based from oldest).
	scrollbackRow: number,
	// Column of the match start.
	colStart: number,
	// Column of the match end (exclusive).
	colEnd: number,
};

// A search query.
export type SearchQuery = {
	text: string,
	caseSensitive: boolean,
	regex: boolean,
};

// Full session state snapshot (returned by `get_session_state`).
export type SessionState = {
	tabs: TabState[],
	activeTabId: TabId,
};

/**
 *  Emitted when the session topology changes in a way that originates
 *  asynchronously (process exit, OSC title, set_active_pane).
 * 
 *  Not emitted for `split_pane` or `close_pane` — those commands return
 *  the updated `TabState` directly (§4.5.2 of ARCHITECTURE.md).
 * 
 *  Uses `#[serde(tag = "type")]` so the TypeScript union discriminant is `type`,
 *  matching the CLAUDE.md IPC event rule for multi-variant events.
 */
export type SessionStateChangedEvent = SessionStateChangedEvent_Serialize | SessionStateChangedEvent_Deserialize;

/**
 *  Emitted when the session topology changes in a way that originates
 *  asynchronously (process exit, OSC title, set_active_pane).
 * 
 *  Not emitted for `split_pane` or `close_pane` — those commands return
 *  the updated `TabState` directly (§4.5.2 of ARCHITECTURE.md).
 * 
 *  Uses `#[serde(tag = "type")]` so the TypeScript union discriminant is `type`,
 *  matching the CLAUDE.md IPC event rule for multi-variant events.
 */
export type SessionStateChangedEvent_Deserialize = { type: "tabCreated"; tab: TabState } | { type: "tabClosed"; 
/**
 *  ID of the tab that was closed. Required by IPC rules: every event
 *  affecting a specific entity must include that entity's ID explicitly.
 */
closedTabId: TabId; 
// Active tab after the close, if any tab remains.
activeTabId: TabId | null } | { type: "tabReordered"; tab: TabState } | { type: "activeTabChanged"; tab: TabState; activeTabId: TabId } | { type: "activePaneChanged"; tab: TabState } | { type: "paneMetadataChanged"; tab: TabState };

/**
 *  Emitted when the session topology changes in a way that originates
 *  asynchronously (process exit, OSC title, set_active_pane).
 * 
 *  Not emitted for `split_pane` or `close_pane` — those commands return
 *  the updated `TabState` directly (§4.5.2 of ARCHITECTURE.md).
 * 
 *  Uses `#[serde(tag = "type")]` so the TypeScript union discriminant is `type`,
 *  matching the CLAUDE.md IPC event rule for multi-variant events.
 */
export type SessionStateChangedEvent_Serialize = { type: "tabCreated"; tab: TabState } | { type: "tabClosed"; 
/**
 *  ID of the tab that was closed. Required by IPC rules: every event
 *  affecting a specific entity must include that entity's ID explicitly.
 */
closedTabId: TabId; 
// Active tab after the close, if any tab remains.
activeTabId?: TabId | null } | { type: "tabReordered"; tab: TabState } | { type: "activeTabChanged"; tab: TabState; activeTabId: TabId } | { type: "activePaneChanged"; tab: TabState } | { type: "paneMetadataChanged"; tab: TabState };

/**
 *  A single cell in a screen snapshot, serialized to the frontend for rendering.
 * 
 *  # Frontend rendering contracts
 * 
 *  The frontend MUST respect the following rules when interpreting a `SnapshotCell`:
 * 
 *  ## Bold color promotion
 *  When `bold == true` and `fg` is `Color::Ansi { index }` with `index` in `[1, 7]`
 *  (the 7 non-black standard colors), the frontend MUST resolve the displayed color
 *  using `index + 8` (the bright variant). Index 0 (black) is **excluded** from
 *  promotion — bold black renders as ordinary black.
 * 
 *  ## Dim (faint)
 *  When `dim == true`, the frontend MUST apply `opacity: var(--term-dim-opacity)`
 *  (design token value: 0.5) to the foreground color. Dim is independent of `bold`
 *  and applies after bold color promotion.
 * 
 *  ## Reverse video
 *  When `inverse == true`, the frontend MUST swap the resolved foreground and
 *  background colors. The swap operates on the **resolved** values — i.e. after
 *  bold color promotion has been applied to `fg`, and after substituting terminal
 *  defaults for any `None` color.
 */
export type SnapshotCell = {
	content: string,
	width: number,
	bold: boolean,
	dim: boolean,
	italic: boolean,
	underline: number,
	blink: boolean,
	inverse: boolean,
	hidden: boolean,
	strikethrough: boolean,
	fg: Color | null,
	bg: Color | null,
	underlineColor: Color | null,
	// OSC 8 hyperlink URI for this cell, if any.
	hyperlink: string | null,
};

// Split direction for `split_pane`.
export type SplitDirection = "horizontal" | "vertical";

// Saved SSH connection configuration (persisted in preferences.json).
export type SshConnectionConfig = {
	id: ConnectionId,
	label: SshLabel,
	host: SshHost,
	port: number,
	username: SshUsername,
	/**
	 *  Path to a private key file.
	 * 
	 *  Structural validation (absolute, no traversal, no control chars, ≤4096 bytes) is enforced
	 *  by `SshIdentityPath::try_from` at IPC deserialization time (SEC-PATH-005).
	 *  File existence and `~/.ssh/` boundary are checked at connection time in
	 *  `lifecycle.rs::open_connection_inner`.
	 */
	identityFile: SshIdentityPath | null,
	// Per-connection OSC 52 write policy override.
	allowOsc52Write?: boolean,
	/**
	 *  Override the keepalive probe interval for this connection (seconds).
	 *  Falls back to `SSH_KEEPALIVE_INTERVAL` (30 s) when absent (FS-SSH-020).
	 */
	keepaliveIntervalSecs: number | null,
	/**
	 *  Override the maximum number of consecutive unanswered keepalive probes
	 *  before the connection is declared lost (FS-SSH-020).
	 *  Falls back to `SSH_KEEPALIVE_MAX_MISSES` (3) when absent.
	 */
	keepaliveMaxFailures: number | null,
};

/**
 *  A validated SSH hostname or IP address.
 * 
 *  Constraints: max 253 bytes, no control characters, valid hostname/IP format.
 */
export type SshHost = string;

/**
 *  A structurally validated SSH identity file path.
 * 
 *  Enforces at serde/construction time: absolute path (starts with `/`),
 *  no `..` components, no control characters, max 4096 bytes.
 * 
 *  Does NOT check file existence or `~/.ssh/` boundary — those are runtime
 *  checks in `lifecycle.rs::open_connection_inner` via
 *  `platform::validation::validate_ssh_identity_path`.
 */
export type SshIdentityPath = string;

/**
 *  A validated SSH connection label (non-empty display name).
 * 
 *  Constraints: max 256 bytes, no control characters, non-empty.
 */
export type SshLabel = string;

// SSH session lifecycle state (§5.2 of ARCHITECTURE.md).
export type SshLifecycleState = 
// TCP connection in progress.
{ type: "connecting" } | 
// SSH handshake and credential exchange.
{ type: "authenticating" } | 
// Session is active.
{ type: "connected" } | 
/**
 *  Session lost due to network drop or keepalive timeout.
 * 
 *  `reason` carries a human-readable explanation (e.g. "keepalive timeout",
 *  "Connection lost: …"). The frontend reads it directly from this variant —
 *  `SshStateChangedEvent` carries no separate top-level reason field.
 */
{ type: "disconnected"; reason: string | null } | 
// User-initiated close or remote exit with code 0.
{ type: "closed" };

/**
 *  Emitted immediately after a successful SSH reconnect.
 * 
 *  The frontend uses this to insert a visual separator in the scrollback so
 *  the user can clearly distinguish output from the previous session and the
 *  new one (FS-SSH-042, UXD §7.19).
 */
export type SshReconnectedEvent = {
	paneId: PaneId,
	// Unix timestamp in milliseconds at the moment of reconnection.
	timestampMs: number,
};

/**
 *  Emitted on every SSH session state transition.
 * 
 *  The disconnect reason, if any, is carried inside
 *  `SshLifecycleState::Disconnected { reason }` — no top-level `reason` field
 *  to avoid the duplication that previously required manual sync.
 */
export type SshStateChangedEvent = {
	paneId: PaneId,
	state: SshLifecycleState,
};

/**
 *  A validated SSH username (non-empty).
 * 
 *  Constraints: max 255 bytes, no control characters, non-empty.
 */
export type SshUsername = string;

/**
 *  Emitted when a deprecated SSH algorithm is detected during the connection
 *  handshake (`ssh-rsa` SHA-1, `ssh-dss`). Non-blocking — for informational
 *  display in the pane or a UI banner.
 */
export type SshWarningEvent = {
	paneId: PaneId,
	// The deprecated algorithm name, e.g. `"ssh-rsa"` or `"ssh-dss"`.
	algorithm: string,
	// Human-readable explanation of why this algorithm is deprecated.
	reason: string,
};

// Identifies a tab in the session registry.
export type TabId = string;

// Serializable tab state — the canonical type returned by IPC commands.
export type TabState = {
	id: TabId,
	// User-defined label. `None` = auto-title from active pane's OSC title.
	label: string | null,
	activePaneId: PaneId,
	// Display order (lower = further left in the tab bar).
	order: number,
	// Pane layout tree.
	layout: PaneNode,
};

/**
 *  Uniform error envelope returned by all Tauri command handlers.
 * 
 *  Serialized to JSON as `{ "code": "...", "message": "...", "detail": "..." }`.
 */
export type TauTermError = {
	/**
	 *  Machine-readable error code (upper-case, underscore-separated, module-prefixed).
	 *  Examples: `PTY_SPAWN_FAILED`, `INVALID_PANE_ID`, `SSH_KEEPALIVE_TIMEOUT`.
	 */
	code: string,
	// Human-readable summary suitable for display to non-technical users (FS-UX-001).
	message: string,
	// Optional technical detail: raw OS error, exit code, system message.
	detail: string | null,
};

/**
 *  Partial update for terminal preferences — only the fields provided are changed.
 * 
 *  Mirrors `AppearancePatch`: field-level merging avoids overwriting unrelated
 *  settings when, e.g., only `scrollback_lines` is changed from the UI.
 */
export type TerminalPatch = {
	scrollbackLines?: number | null,
	allowOsc52Write?: boolean | null,
	wordDelimiters?: WordDelimiters | null,
	bellType?: BellType | null,
	confirmMultilinePaste?: boolean | null,
};

// Terminal behavior preferences.
export type TerminalPrefs = {
	// Maximum scrollback lines per pane.
	scrollbackLines?: number,
	// Allow OSC 52 clipboard write for local sessions.
	allowOsc52Write?: boolean,
	// Characters treated as word delimiters for double-click selection.
	wordDelimiters?: WordDelimiters,
	// Bell notification type.
	bellType?: BellType,
	/**
	 *  Show a confirmation dialog before pasting multi-line text when bracketed
	 *  paste is inactive (FS-CLIP-009). Default: `true`. The user can disable
	 *  it via the "Don't ask again" toggle in the paste dialog.
	 */
	confirmMultilinePaste?: boolean,
};

/**
 *  A validated theme name (non-empty).
 * 
 *  Constraints: max 128 bytes, no control characters, non-empty.
 */
export type ThemeName = string;

// A user-defined color theme.
export type UserTheme = {
	name: string,
	// ANSI palette: 16 colors (0–15). Each entry is an RGB hex string (e.g., "#1e1e2e").
	palette: [string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string],
	foreground: string,
	background: string,
	cursorColor: string,
	selectionBg: string,
	/**
	 *  Terminal line height multiplier (FS-THEME-010). Range: 1.0–2.0.
	 *  `None` means use the global default (`--line-height-terminal` token).
	 */
	lineHeight?: number | null,
};

/**
 *  Validated word delimiter characters (may be empty).
 * 
 *  Constraints: max 128 bytes, no control characters.
 */
export type WordDelimiters = string;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

